name: ci
on:
  push:
    branches:
    - main

permissions:
  contents: write
  security-events: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  packages: write

jobs:
  push-artifact:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@latest
            
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Git tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Push rego policies
        id: push_policies
        run: |
          GIT_TAG=${{ steps.get_tag.outputs.tag }}
          GENVAL_OUTPUT=$(genval artifact push --reqinput ./dockerfile_policies \
          --dest ghcr.io/santosh1176/bookstore-api/dockerfile_policies:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "::set-output name=artifact_url::ghcr.io/intelops/policyhub/genval/dockerfile_policies:${GIT_TAG}"

      - name: Use artifact URL
        run: |
          echo "Artifact URL is: ${{ steps.push_policies.outputs.artifact_url }}"
