name: ci
on:
  push:
  branches: 
      - main
    # if: "contains(github.event.head_commit.modified, 'dockerfile_policies/**')"
      
permissions:
  contents: write
  security-events: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  packages: write

jobs:
  push-artifacts:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      
      - name: Install genval
        run: go install github.com/intelops/genval@91ef4df
            
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print jq version
        run: jq --version
        

      - name: Fetch Git tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Push Dockerfile policies
        id: push_dockerfile_policies
        if: "contains(github.event.commit.modified, 'dockerfile_policies/**')"

        run: |
          echo ${{ toJSON(github.event.commit.modified) }}
        # run: |
        #   GIT_TAG=${{ env.tag }}
        #     GENVAL_OUTPUT=$(genval artifact push --reqinput ./dockerfile_policies \
        #   --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
        #   --annotations="authors=santoshdts")
        #   echo "${GENVAL_OUTPUT}"
        #   echo "dockerfile_artifact_url=oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG}" >> $GITHUB_ENV
