name: image-insights

on:
  # The schedule will trigger at 0900 UTC timezone
  # schedule:
  #   - cron: "0 08 * * *"
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write
  id-token: write
# actions: wrgccte
# pull-requests: write

jobs:
  publish-insights:
    env:
      REGISTRY: ghcr.io
      ORG: open-containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: ansible

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: "0"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: "santoshkal"
          password: ${{ secrets.DOCKER_SECRET}}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true
          sarif-file: "./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-cves.json"

      - name: Debug Docker Secret
        run: echo "DOCKER_SECRET is set"
        if: ${{ secrets.DOCKER_SECRET != '' }}
