name: image-insights

on:
  # The schedule will trigger at 0900 UTC timezone
  # schedule:
  #   - cron: "0 08 * * *"
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write
  id-token: write
# actions: wrgccte
# pull-requests: write

jobs:
  publish-insights:
    runs-on: ubuntu-latest
    # env:
    #   REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: "0"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: "santoshkal/ollama-base:v0.3.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true
          sarif-file: "./ansible-attestations/ollama-base-cves.json"
          dockerhub-user: santoshkal
          dockerhub-password: ${{ secrets.DOCKER_SECRET }}
      - name: Stage files
        run: |
          git add .

      - uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "Add Provenance files"
          repo: ${{ github.repository }}
          branch: "main"
          # branch: ${{ matrix.image.name }}-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{secrets.GHCR_PAT}}
