name: Dockerfile Workflow

on:
  push:
    branches:
      - main
    paths:
      - "dockerfile_policies/**"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Check PWD
        run: echo "I am here $(pwd)"

      - name: Fetch Initial version
        id: init_version
        run: |
          ./.github/workflows/get-version.sh

      - name: Set Init-Version
        run: |
          echo "INIT_TAG=${{ steps.init_version.outputs.new_version }}"

      - name: Install genval
        run: go install github.com/intelops/genval@main
      - name: Genval version
        run: echo "genval version"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag a release
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: "main"
          DEFAULT_BUMP: "patch"
          INITIAL_VERSION: ${INIT_TAG}

      - name: Get new tag
        run: echo "tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Push Dockerfile policies
        id: push_dockerfile_policies
        run: |
          GIT_TAG=${{ env.tag }} 
          genval artifact push --reqinput ./dockerfile_policies/ \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
            --annotations="authors=santoshdts"
