name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dockerfile:
              - added|modified: 'dockerfile_policies/**'

      - name: Push Dockerfile policies
        if: ${{ steps.filter.outputs.dockerfile ==  'true' }}
        id: push_dockerfile_policies
        run: |
          genval artifact push --reqinput ./dockerfile_policies/ \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:v0.0.58 \
            --annotations="authors=santoshdts"
