name: Dockerfile Workflow

on:
  push:
    branches:
      - prod
    paths:
      - "dockerfile_policies/**"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag a release
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          release_branches: prod,main
          default_bump: patch

      - name: Get new tag
        run: echo "New tag is ${{ steps.tag_version.outputs.new_version }}"

      - name: Push Dockerfile policies
        if: ${{ steps.filter.outputs.dockerfile ==  'true' }}
        id: push_dockerfile_policies
        run: |
          GIT_TAG=${{ env.tag }} 
          genval artifact push --reqinput ./dockerfile_policies/ \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
            --annotations="authors=santoshdts"
