name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - "terraform_policies/**"
      - "dockerfile_policies/**"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        policy:
          - name: dockerfile_policies
            path: dockerfile_policies/**
            version-file: dockerfile_version.env
            artifact-name: dockerfile_policies
            output-file: DOCKERFILE_POLICIES.env
          - name: terraform_policies
            path: terraform_policies/**
            version-file: terraform_version.env
            artifact-name: terraform_policies
            output-file: TERRAFORM_POLICIES.env

    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
          echo "::set-output name=matrix::$matrix"
        id: matrix
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Check path updates
        id: changes
        uses: dorny/paths-filter@v3
        with:
          base: main
          filters: |
            src:
              - ${{ matrix.policy.path }}

  push-artifacts:
    runs-on: ubuntu-latest
    needs: [check-updates]
    steps:
      - name: Dump matrix context
        id: matrix
        run: echo 'matrix="$(cat */matrix | jq -c --slurp .)"'
