name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - "terraform_policies/**"
      - "dockerfile_policies/**"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Check path updates
        id: changes
        uses: dorny/paths-filter@v3
        with:
          base: main
          filters: |
            src:
              - "terraform_policies/**"
              - "dockerfile_policies/**"
    outputs:
      changed-parts: ${{ steps.chenges.outputs.changes }}

  push-artifacts:
    needs: check-updates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        policy:
          - name: dockerfile_policies
            path: dockerfile_policies/**
            version-file: dockerfile_version.env
            artifact-name: dockerfile_policies
            output-file: DOCKERFILE_POLICIES.env
          - name: terraform_policies
            path: terraform_policies/**
            version-file: terraform_version.env
            artifact-name: terraform_policies
            output-file: TERRAFORM_POLICIES.env

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false
      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version tag
        run: |
          echo "tag=$(./.github/get_version.sh ./.github/versions/${{ matrix.policy.version-file }})" >> $GITHUB_ENV
      - name: Push Dockerfile policies
        id: push_policies
        run: |
          if ${{ needs.check-updated.outputs.changed-parts }}
          GIT_TAG=${{ env.tag }}
          GENVAL_OUTPUT=$(genval artifact push --reqinput ${{ matrix.policy.path }} \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/${{ matrix.policy.artifact-name }}:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "${{ matrix.policy.output-file }}=oci://ghcr.io/santoshkal/ci-test/artifcts/${{ matrix.policy.artifact-name }}:${GIT_TAG}" >> $GITHUB_ENV
      - name: Write policy URL
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ${{ matrix.policy.path }}/newversion.txt
          write-mode: overwrite
          contents: |
            # GitHub generated file
            # Please do not modify or delete this file
            ${{ env[matrix.policy.output-file] }}
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Overwritten by Github Actions - ${date}"
