name: CI Workflow

on:
  push:
    paths:
      - 'dockerfile_policies/**'
jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes and tag push
        id: check_conditions
        run: |
          if [[ ! $GITHUB_REF =~ ^refs/tags/v.*$ ]]; then
            echo "This push is not a tag push. Exiting."
            exit 1
          fi

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if [[ ! $(echo "$CHANGED_FILES" | grep -E '^(dockerfile_policies/**)/') ]]; then
            echo "No changes in the specified paths. Exiting."
            exit 1
          fi


      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      
      - name: Install genval
        run: go install github.com/intelops/genval@91ef4df
            
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Git tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Push Dockerfile policies
        id: push_dockerfile_policies
        run: |
          if: "startsWith(github.ref, 'refs/tags/v'"
          GIT_TAG=${{ env.tag }}
            GENVAL_OUTPUT=$(genval artifact push --reqinput ./dockerfile_policies \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "dockerfile_artifact_url=oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG}" >> $GITHUB_ENV
