name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'terraform_policies/**'
      - 'dockerfile_policies/**'

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  push-artifacts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        policy-type: [
        dockerfile_policies,
        terraform_policies,
        ]
      include:
        - policy-type: dockerfile_policies/**
          path: ./dockerfile_policies
          version-file: dockerfile_version.env
          artifact-name: dockerfile_policies
        - policy-type: terraform_policies
          path: terraform_policies/**
          version-file: terraform_version.env
          artifact-name: terraform_policies

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false
      #
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - ${{ matrix.path }}

      - if: steps.changes.outputs.src == 'true'
        run: |
          echo "tag=$(./.github/get_version.sh ./.github/versions/${{ matrix.version-file }})" >> $GITHUB_ENV

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Dockerfile policies
        id: push_policies
        run: |
          GIT_TAG=${{ env.tag }}
            GENVAL_OUTPUT=$(genval artifact push --reqinput ${{ matrix.path }} \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/${{ matrix.artifact-name }}:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "${{ matrix.artifact-name | upper }}=oci://ghcr.io/santoshkal/ci-test/artifcts/${{ matrix.artifact-name }}:${GIT_TAG}" >> $GITHUB_ENV

      - name: Write policy URL
        uses: "DamianReeves/write-file-action@master"
        with:
          path: terraform_policies/newversion.txt
          write-mode: overwrite
          contents: |
            # GitHub generated file
            # Please do not modify or delete this file
            ${{ env[matrix.artifact-name | upper] }}

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Overwritten by Github Actions - ${date}"
