name: Terraform Workflow

on:
  push:
    branches:
      - terraform-policies
    paths:
      - "terraform_policies/**"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false
      #
      # - name: Fetch Initial version
      #   id: init_version
      #   run: |
      #     ./.github/workflows/get_version.sh
      #
      # - name: Set Init-Version
      #   id: set_init_version
      #   run: echo "INIT_TAG=${{ steps.init_version.outputs.new_version }}" >> $GITHUB_ENV
      #
      # - name: Check Init Version
      #   run: echo "Init tag ${{ env.INIT_TAG }}"

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag a release
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # INITIAL_VERSION: ${{ env.INIT_TAG }}
          WITH_V: true
          RELEASE_BRANCHES: "terraform-policies"
          DEFAULT_BUMP: "patch"
          TAG_CONTEXT: branch

      - name: Get new tag
        run: echo "tag=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Push Terraform policies
        id: push_terraform_policies
        run: |
          GIT_TAG=${{ env.tag }} 
          genval artifact push --reqinput ./terraform_policies/ \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/terraform_policies:${GIT_TAG} \
            --annotations="authors=santoshdts"
