name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - "terraform_policies/**"
      - "dockerfile_policies/**"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        policy:
          - name: dockerfile_policies
            path: dockerfile_policies/**
            version-file: dockerfile_version.env
            artifact-name: dockerfile_policies
            output-file: DOCKERFILE_POLICIES.env
          - name: terraform_policies
            path: terraform_policies/**
            version-file: terraform_version.env
            artifact-name: terraform_policies
            output-file: TERRAFORM_POLICIES.env
    outputs:
      matrix: ${{ steps.set-matrix-output.outputs.matrix }}

    steps:
      - name: Set matrix output
        id: set-matrix-output
        run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "::set-output name=matrix::$matrix"

      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Check path updates
        id: changes
        uses: dorny/paths-filter@v3
        with:
          base: main
          filters: |
            src:
              - ${{ matrix.policy.path }}

  push-artifacts:
    runs-on: ubuntu-latest
    needs: [check-updates]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.check-updates.outputs.matrix)}}

    steps:
      - name: Debug Matrix values
        id: debug-matrix-values
        run: |
          echo "MATRIX: ${{matrix.policy.name}}"
          echo "ACTUAL_MATRIX: ${{needs.check-updates.outputs.matrix}}"
          echo "PATH: ${{needs.check-updates.outputs.matrix}}"
          echo "JAON_PATH: ${{ matrix.policy.path }}"
