name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - "terraform_policies/**"
      - "dockerfile_policies/**"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  check-updates:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        policy:
          - name: dockerfile_policies
            path: dockerfile_policies/**
            version-file: dockerfile_version.env
            artifact-name: dockerfile_policies
            output-file: DOCKERFILE_POLICIES.env
          - name: terraform_policies
            path: terraform_policies/**
            version-file: terraform_version.env
            artifact-name: terraform_policies
            output-file: TERRAFORM_POLICIES.env

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - ${{ matrix.policy.path }}

  push-artifacts:
    runs-on: ubuntu-latest
    needs: check-updates
    if: needs.check-updates.steps.changes.outputs.src == 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Dockerfile policies
        id: push_policies
        run: |
          GIT_TAG=${{ env.tag }}
          GENVAL_OUTPUT=$(genval artifact push --reqinput ${{ needs.check-updates.matrix.policy.path }} \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/${{ needs.check-updates.matrix.policy.artifact-name }}:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "${{ matrix.policy.output-file }}=oci://ghcr.io/santoshkal/ci-test/artifcts/${{ needs.check-updates.matrix.policy.artifact-name }}:${GIT_TAG}" >> $GITHUB_ENV

      - name: Write policy URL
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ${{ matrix.policy.path }}/newversion.txt
          write-mode: overwrite
          contents: |
            # GitHub generated file
            # Please do not modify or delete this file
            ${{ env[needs.check-updates.matrix.policy.output-file] }}

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Overwritten by Github Actions - ${date}"
