name: CI Workflow

on:
  push:
    paths:
      - "dockerfile_policies/**"
    tags:
      - "v*"

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Git tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Check for changes in dockerfile_policies
        id: check_conditions
        run: |
          CHANGED_FILES=$(git diff --name-only origin| grep -E '^dockerfile_policies/')
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No changes in the specified paths. Exiting."
            exit 1
          fi

      - name: Push Dockerfile policies
        if: startsWith(github.ref, 'refs/tags/v')
        id: push_dockerfile_policies
        run: |
          GIT_TAG=${{ env.tag }}
          GENVAL_OUTPUT=$(genval artifact push --reqinput ./dockerfile_policies \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
            --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "dockerfile_artifact_url=oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG}" >> $GITHUB_ENV
