name: Print GitHub Event Payload

on: 
  push:

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print GitHub event payload
        run: |
          echo "GitHub Event Payload:"
          echo '${{ toJson(github.event) }}' | jq '.'
          
      - name: Print modified files
        run: |
          echo "Modified files:"
          echo '${{ toJson(github.event.head_commit.modified) }}' | jq '.commits[].modified'
