name: ci
on:
  push:
    branches:
      - main
    paths:
      - 'dockerfile-policies/**'
    tags:
    - 'v*'
    if: |
      ${{ ("startsWith(github.ref, 'refs/tags/')) &&
      (github.ref ==  'refs/heads/main') &&
      contains(github.event.head_commit.modified, 'terraform_policies/**') }}
      
permissions:
  contents: write
  security-events: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  packages: write

jobs:
  push-artifact:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      
      - name: Install genval
        run: go install github.com/intelops/genval@91ef4df
            
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Git tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Push rego policies
        id: push_policies
        run: |
          GIT_TAG=${{ env.tag }}
            GENVAL_OUTPUT=$(genval artifact push --reqinput ./dockerfile_policies \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "artifact_url=oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG}" >> $GITHUB_ENV
      - name: Use artifact URL
        run: |
          echo "Artifact URL is: ${{ env.artifact_url }}"
