name: Terraform  Workflow

on:
  push:
    branches:
      - prod
    paths:
      - terraform_policies/**"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag a release
        id: tag_version
        uses: mathieudutour/github-tag-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          default_bump: patch
          create_annotated_tag: true

      - name: Get new tag
        run: echo "New tag is ${{ steps.tag_version.outputs.new_version }}" >> $GITHUB_ENV
        run: echo "New tag is ${{ steps.tag_version.outputs.new_version }}"

      - name: Push Terraform policies
        if: ${{ steps.filter.outputs.dockerfile ==  'true' }}
        id: push_terraform_policies
        run: |
            GIT_TAG=${{env.tag }} 
            genval artifact push --reqinput ./terraform_policies/ \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/terraform_policies:${GIT_TAG} \
            --annotations = "authors=santoshdts"
