name: CI Workflow

on:
  push:
    paths:
      - dockerfile_policies/**

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Dockerfile policies
        id: push_dockerfile_policies
        run: |
          GIT_TAG=${{ env.tag }}
          genval artifact push --reqinput ./dockerfile_policies/ \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${{ github.ref }} \
          --annotations="authors=santoshdts"
