name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - "terraform_policies/**"
      - "dockerfile_policies/**"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  check-updates:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        policy:
          - name: dockerfile_policies
            path: dockerfile_policies/**
            version-file: dockerfile_version.env
            artifact-name: dockerfile_policies
            output-file: DOCKERFILE_POLICIES.env
          - name: terraform_policies
            path: terraform_policies/**
            version-file: terraform_version.env
            artifact-name: terraform_policies
            output-file: TERRAFORM_POLICIES.env

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Check path updates
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - ${{ matrix.policy.path }}

      - name: Set output if changes detected
        id: set-changes-output
        run: |
          echo "changes=${{ steps.changes.outputs.src }}" >> $GITHUB_ENV
          echo "::set-output name=changes::${{ steps.changes.outputs.src }}"

  push-artifacts:
    runs-on: ubuntu-latest
    needs: check-updates
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Debug outputs
        run: |
          echo "Matrix Policy: ${{ toJSON(needs.check-updates.outputs) }}"
          echo "Changes: ${{ needs.check-updates.outputs.changes }}"
