name: CI Workflow

on:
  push:
    paths:
      - "dockerfile_policies/**"
    tags:
      - "v*"

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Install genval
        run: go install github.com/intelops/genval@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Git tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            with:
              src:
                - 'dockerfile_policies/**'

      - name: Push Dockerfile policies
        if: steps.filter.outputs.src ==  'true'
        id: push_dockerfile_policies
        run: |
          echo ""
          GIT_TAG=${{ env.tag }}
          genval artifact push --reqinput ./dockerfile_policies/ \
            --dest oci://ghcr.io/santoshkal/ci-test/artifcts/dockerfile_policies:${GIT_TAG} \
            --annotations="authors=santoshdts"
