name: ci
on:
  push:
    tags: 
      - 'v*'
    # if: "contains(github.event.head_commit.modified, 'dockerfile_policies/**')"
      
permissions:
  contents: write
  security-events: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  packages: write

jobs:
  push-artifacts:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      # 
      - name: Install genval
        run: go install github.com/intelops/genval@91ef4df
      #       
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Fetch Git tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Push Terraform
        id: push_terraform_policies
        with:
          filters: |
            src: 'terraform_policies/**'
        if: steps.push_terraform_policies.outputs.src ==  true
        run: |
          GIT_TAG=${{ env.tag }}
            GENVAL_OUTPUT=$(genval artifact push --reqinput ./terraform_policies \
          --dest oci://ghcr.io/santoshkal/ci-test/artifcts/terraform_policies:${GIT_TAG} \
          --annotations="authors=santoshdts")
          echo "${GENVAL_OUTPUT}"
          echo "terraform_artifact_url=oci://ghcr.io/santoshkal/ci-test/artifcts/terraform_policies:${GIT_TAG}" >> $GITHUB_ENV

